---
title: "Melhores práticas"
---

Está é minha <a href="CV.pdf#" class="download" title="Download CV as PDF">Súmula curricular</a>. Mas como nem tudo cabe no [Lattes](http://lattes.cnpq.br/2582841591375626), eu relato a seguir minhas melhores práticas que contribuem para o desenvolvimento científico, tecnológico e educacional e que me permitiram seguir um caminho por uma **sociolinguística socialmente sensível** e alinhada às práticas de [Ciência Aberta](https://rkofreitag.github.io/aberta.html)

## **Pistas do processamento da variação linguística**

Campo emergente e interdisciplinar, com interface com a Psicolinguística e as Ciências Cognitivas, os estudos de processamento da variação linguística visam desvelar o custo cognitivo do processamento de um dado traço linguístico, considerando os padrões de recorrência da produção e os padrões de julgamento da percepção. 

O esforço cognitivo associado ao processamento de uma variante pode ser medido de maneira direta, com o tempo de resposta, ou indireta, com os reparos e correções do falante. Os resultados destas medidas podem ser obtidos por diferentes desenhos experimentais, cujas tarefas permitem o controle do contexto para minimizar efeitos de outras variáveis intervenientes, assim como possibilitam a aferição dos efeitos de diferentes situações para um mesmo alvo. A conjugação de tarefas com medidas implícitas e explícitas, assim como resultados obtidos por métodos observacionais pode apontar para a atuação de forças cognitivas implícitas, como a consciência sociolinguística, e explícitas, como o prescritivismo, ou, ainda, pela conjunção das duas. 

- O processamento da variação linguística é controlado ou automático? 
- Qual a relação entre estereótipos, marcadores e indicadores com o tipo de processamento cognitivo? 
- O estudo do processamento da variação linguística pode dar respostas a estas questões 

<details>
  <summary markdown="span"> *Clique aqui se quiser conhecer detalhes do desenvolvimento deste projeto e seus produtos* </summary>

- Com Marije Soto, organizei um dossiê para a Revista de *Estudos da Linguagem* intitulado [**Processamento da variação linguística**](http://www.periodicos.letras.ufmg.br/index.php/relin/issue/view/808/showToc), que reúne 14 artigos tratando do tema.
  
- Um deles é [**Processamento da variação linguística: desafios para integrar aquisição, diversidade e compreensão em um modelo de língua**](http://www.periodicos.letras.ufmg.br/index.php/relin/article/view/40123/pdf), em que discutimos os desafios de conciliar o controle exigido em pesquisa experimental com o paradoxo do observador da sociolinguística, além das limitações decorrentes da tecnologia disponível para o estudo, assim como da construção de um modelo de língua que envolva diversidade e estrutura.
</details>
<p>&nbsp;</p>


## **Saliência, percepção e atitudes sociolinguísticas**

O que seria do vermelho se todo mundo só gostasse do amarelo? Por que uns gostam de vermelho e outros de amarelo? Transpondo para a língua, por que certos traços linguísticos são bem apreciados e avaliados, e outros são o contrário? Este é o tema do meu projeto de Produtividade em Pesquisa atual. 
Em termos metodológicos, para identificar a que significados sociais uma variante está associada, a abordagem sociolinguística considera fenômenos de variação do ponto de vista da produção (quem usa? em que contextos?) e do ponto de vista da percepção (como os falantes julgam as variantes? a quem eles as associam?). Um artifício conceitual utilizado para articular as duas perspectivas de abordagem é a saliência. No período de 2017 a 2020, meu foco de pesquisa foi investigar a relação entre saliência cognitiva e consciência social, testando diversas abordagens e em diversos fenômenos. 

<details>
  <summary markdown="span"> *Clique aqui se quiser conhecer detalhes do desenvolvimento deste projeto e seus produtos* </summary>

- Os achados do desenvolvimento deste projeto foram sistematizados para a leitura, no artigo [**A sociolinguística da leitura**](https://revistaseletronicas.pucrs.br/index.php/letronica/article/view/37508/26431), em linguagem clara e acessível, com possibilidade de transladação didática para a aula de Língua Portuguesa. 

- No artigo [**Saliência estrutural, distribucional e sociocognitiva**](https://doi.org/10.4025/actascilangcult.v40i2.41173), discuti os diferentes tipos de saliência que atuam no processamento da variação linguística, tanto na produção quanto na percepção. 

- Na produção, observamos, eu, [Bruno Pinheiro](http://lattes.cnpq.br/0308930203332747) e [Paloma Cardoso](http://lattes.cnpq.br/5477985767644106), a [**Saliência na conservação de /d/ no segmento /ndo/: efeitos sociais e estilísticos**](http://dx.doi.org/10.22409/gragoata.2018n46a1123). 

- A variação entre *nós* e *a gente* é um fenômeno que permite contrastar a percepção e produção, como no artigo [**Uso, crença e atitudes na variação na primeira pessoa do plural no Português Brasileiro**](https://www.scielo.br/scielo.php?pid=S0102-44502016000400889&script=sci_abstract&tlng=pt), ou verificar os efeitos de fatores externos no julgamento em testes de reação subjetiva, como apresentamos, eu, [Paloma Cardoso](http://lattes.cnpq.br/5477985767644106) e [Paula Yasmim Gois](http://lattes.cnpq.br/3958889695579348), no capítulo [**A percepção da variação na primeira pessoa do plural: efeitos do monitoramento estilístico e da urbanização**](https://www.researchgate.net/publication/329911004_A_percepcao_da_variacao_na_primeira_pessoa_do_plural_efeitos_do_monitoramento_estilistico_e_da_urbanizacao).

- Mas nenhum fenômeno supera a palatalização para o estudo dos efeitos de saliência no processamento da variação. Junto com [Adelmileise de Oliveira](http://lattes.cnpq.br/3192180180719815), neste capítulo mostramos [**Percepção e atitudes linguísticas em relação às africadas pós-alveolares em Sergipe**](https://openaccess.blucher.com.br/article-details/percepcao-e-atitudes-linguisticas-20312) considerando os dois contextos: palatalização regressiva e palatalização progressiva em um teste de reação subjetiva do tipo *verbal guise*. Os resultados foram refinados para considerar os efeitos da concordância entre participantes e o método está descrito em [**Kappa statistic for judgment agreement in Sociolinguistics**](http://dx.doi.org/10.17851/2237-2083.0.0.1591-1612), cuja versão preliminar foi apresentada no [**46 NWAV**](Production and perception of affricate /t/ and /d/ in Northeastern Brazil In: 46 New Ways of Analyzing Variation - NWAV).

- Pensando em estratégias metodológicas para medir os efeitos da sensibilidade à frequência de um traço linguístico (especificamente a palatalização regressiva e progressiva), repliquei o experimento do *monitor sociolinguístico*, cujos resultados foram apresentados no [**47 NWAV**](https://s18798.pcdn.co/nwav47/wp-content/uploads/sites/7918/2018/10/NWAV47Program-final2-1.pdf) e selecionado para publicação no volume do periódico UPenn WP dedicado aos trabalhdos do evento: [**Effects of the linguistic processing: palatals in Brazilian Portuguese and the sociolinguistic monitor**](https://repository.upenn.edu/pwpl/vol25/iss2/4/).

- No estudo da variação linguística, por limitação metodológica, uma única variável costuma ser isolada para seu comportamento ser observado, tanto na produção como na percepção. Por isso, junto com [Victor Renê Andrade Souza](http://lattes.cnpq.br/6402436577817417), realizamos um experimento com um conjunto de traços linguísticos variáveis, me diferentes níveis de consciência. [**Discriminação de palavras e efeitos da variação linguística**](http://comissoes.sbc.org.br/ce-pln/stil2019/proceedings-stil-2019-Final-Publicacao.pdf) apresenta estes resultados, considerando o efeito do tempo de resposta.

- Em busca de diversidade metodológica para desvelar os efeitos da saliência no processamento, observei pistas indiretas, como [**Reparos na leitura em voz alta como pistas de consciência sociolinguística**](https://www.researchgate.net/publication/342346890_Reparos_na_leitura_em_voz_alta_como_pistas_de_consciencia_sociolinguistica), que apontam para padrões de apreciação social para além de indicadores, marcadores e estereótipos. 
  
- Outros domínios da língua também são sensíveis ao nível de consciência, como eu e [Bruno Pinheiro](http://lattes.cnpq.br/0308930203332747) mostramos no artigo [**Estereótipos na concordância de gênero em profissões: efeitos de frequência e saliência**](https://revistas.ufrj.br/index.php/rl/article/view/31637/20599), com efeitos inclusive no tempo de leitura, como em [**Leitura de palavras-tabu e efeitos de gênero**](https://openaccess.blucher.com.br/article-details/12-22195)
</details>
<p>&nbsp;</p>

## **Tecnologias sociais para formalização e ressignificação de práticas culturais em Aracaju/SE**

A participação no projeto *Tecnologias sociais para formalização e ressignificação de práticas culturais em Aracaju/SE*, financiado pelo edital CAPES/FAPITEC/SE 05/2014, Programa de Integração da Ciência, Tecnologia e Inovação com a Educação Básica – Núcleos de CTI-EB, foi uma das experiências mais desafiadoras que enfrentei. 

Na perspectiva da pedagogia culturalmente sensível (Erickson, 1987), segundo a qual a escola deve partir dos valores socioculturais da comunidade onde está localizada, buscamos investigar um arranjo produtivo local ainda não sistematizado, as comidas tradicionais. 
 
A partir da identificação de valores, práticas e produções culturais no entorno de três comunidades escolares, fomentamos o desenvolvimento de tecnologias sociais relacionadas à produção de alimentos e o seu comércio informal. Desenvolvemos uma proposta de abordagem para identificar os alimentos tradicionais e típicos sergipanos, a partir do que é consumido diariamente, na forma do curso *Em busca da comida mais sergipana*. Foram realizadas oficinas para instrumentalizar os alunos a registrarem seus hábitos alimentares e da sua família, envolvendo conteúdos de Língua Portuguesa e Matemática no processo de identificação e sistematização das receitas. 

<details>
  <summary markdown="span"> *Clique aqui se quiser conhecer detalhes do desenvolvimento deste projeto e seus produtos* </summary>

- Curso [**Em busca da comida mais sergipana**](http://ri.ufs.br/jspui/handle/riufs/13465), disponível no Repositório Institucional da Universidade Federal de Sergipe, que pode ser replicado em outras escolas ou adaptado para outras realidades.

- Inicialmente pensado como manual para a orientação da equipe, o livro [**Documentação Sociolinguística, coleta de dados e ética em pesquisa**](http://www.livraria.ufs.br/produto/documentacao-sociolinguistica-coleta-de-dados-e-etica-em-pesquisa/), publicado pela Editora da Universidade Federal de Sergipe e disponível gratuitamente para *download*, em que são apresentados as diretrizes de documentação sociolinguística em espaço escolar, bem como orientações para atendimento aos preceitos de ética em pesquisa científica. 

- Capítulo [**Processos fonológicos que passam da fala para a leitura**](http://www.livraria.ufs.br/produto/leitura-escrita-e-literatura-intersecoes-e-convergencias/), do livro organizado por [Isabel Azevedo](http://lattes.cnpq.br/0314316437786531) e [Alberto Roiphe](http://lattes.cnpq.br/1857856300373125) publicado pela Editora da Universidade Federal de Sergipe e disponível gratuitamente para *download*, em que são analisados processos fonológicos variáveis na fala e na leitura dos estudantes das escolas envolvidas no projeto que participaram da ação de documentação linguística. Estes resultados subsidiaram a proposta de controle de fluência em leitura e diagnóstico de perfil de leitor.

- Artigo [**Pistas dos processos de decodificação que levam à compreensão da leitura**](https://revistaseletronicas.pucrs.br/ojs/index.php/fale/article/view/32509), publicado na revisa Letras de Hoje, em coautoria com minha orientanda de doutorado [Alessandra Pereira Gomes Machado](http://lattes.cnpq.br/2820872438732446), em que apresentamos uma proposta de diagnóstico de perfil de leitor, considerando as pistas de processos de automaticidade na decodificação que levam à compreensão da leitura, com a participação de estudantes da educação básica das escolas envolvidas no projeto.

- Artigo [**Enem: motivações e expectativas de estudantes da rede pública estadual de Sergipe**](https://www.scientiaplena.org.br/sp/article/view/3466), resultado de um trabalho selecionado para apresentação no Encontro Nacional Ciência e Habilidades Socioemocionais (CHA-SE),em 2016, e posteriormente publicado na revista Scientia Plena, e que foi desenvolvido junto com os bolsistas de Iniciação Científica vinculados ao projeto em duas das escolas, Colégio Estadual Atheneu Sergipense e Colégio Estadual Ministro Petrônio Portela, avaliando expectativas prévias e posteriores à realização do Enem. Os resultados evidenciam as diferenças entre as escolas.

Além destes produtos, a formação de recursos humanos foi um diferencial: [Alessandra Machado](http://ri.ufs.br/jspui/handle/riufs/10982) e [Andréa Matos](http://ri.ufs.br/jspui/handle/riufs/9199) desenvolveram suas teses de doutorado, [Rosângela Barros](http://ri.ufs.br/jspui/handle/riufs/5701) desenvolveu sua dissertação de mestrado, e três bolsistas de Iniciação Científica do projeto atualmente são mestrandos: [Paloma Batista Cardoso](http://lattes.cnpq.br/5477985767644106), [Victor Renê Andrade Souza](http://lattes.cnpq.br/6402436577817417) e [Lucas Santos Silva](http://lattes.cnpq.br/1099393463964639), que foi agraciado em [2018](https://fapitec.se.gov.br/static/files/73/X%20PRÊMIO%20JOÃO%20RIBEIRO%20-%20RESULTADO%20FINAL.pdf) e em [2017](https://fapitec.se.gov.br/encerrados/129/EDITAL%2004.2017%20PREMIO) com o Prêmio João Ribeiro de Divulgação Científica na categoria Jovem Cientista, com produtos derivados deste projeto.

</details>

<p>&nbsp;</p>

## **Gênero, polidez e variação linguística** & **Mulheres, linguagem e poder: estudos de gênero na sociolinguística brasileira**

Entre 2012 e 2016, coordenei dois projetos que tiveram como temática o tratamento das relações de gênero na Sociolinguística. No meu projeto de Produtividade em Pesquisa, *Gênero, polidez e variação linguística*, o ponto de partida foi a crença de que mulheres são mais polidas, nem falam palavrões. Será? E se não, por que existe essa percepção? Os fatores pragmáticos, como o efeito do entrevistador na fala do entrevistado, que pode ser medido quanto à polidez decorrente das relações de poder e de solidariedade estabelecidas entre entrevistador e entrevistado e em relação ao sexo/gênero demandam o desenvolvimento de estratégias metodológicas específicas, com um protocolo de de documentação para captar efeitos no uso que permitam evidenciar o perfil de gênero associado às variantes linguísticas em função dos papéis sociais. 

Na mesma linha metodológica, o projeto *Mulheres, linguagem e poder: estudos de gênero na sociolinguística brasileira*, financiado pelo CNPq e pela infelizmente extinta Secretaria Nacional de Políticas para as Mulheres, e coordenado conjuntamente com [Cristine Severo](http://lattes.cnpq.br/3566456623347060), também estava alinhado às questões  metodológicas. Considerando a linguagem e o papel contemporâneo das mulheres e das relações de gênero, discutimos ajustes teórico-metodológicos no campo da Sociolinguística desenvolvida no Brasil para oferecer um instrumental de pesquisa atualizado, especificamente, o papel do sexo/gênero na Sociolinguística no Brasil atual.
Considero este empreendimento de pesquisa crucial para a consolidaçõ de minha carreira e de me permitir avançar não só no plano acadêmico, mas no plano das relações humanas, contribuindo para uma ciência engajada socialmente.

Os resultados do projeto foram compilados no livro [**Mulheres, Linguagem e Poder - Estudos de Gênero na Sociolinguística Brasileira**](https://openaccess.blucher.com.br/article-list/mulheres-linguagem-e-poder-287/list#undefined), disponível para download gratuitamente.

<details>
  <summary markdown="span"> *Clique aqui se quiser conhecer outros detalhes do desenvolvimento destes projetos e seus produtos* </summary>

- O capítulo [**(Re)Discutindo Sexo/Gênero na Sociolinguística**](https://openaccess.blucher.com.br/article-details/rediscutindo-sexognero-na-sociolingustica-19654) traça um panorama teórico e metodológico do tratamento desta variável nos estudos sociolinguísticos brasileiros, e dá os direcionais para o trabalho do grupo quanto ao tratamento desta categoria, inspirando ações de documentação linguística que considerem a gradiência de gênero em termos de identidade, orientação e expressão, conhecido como [*Biscoito do gênero*](https://www.genderbread.org/wp-content/uploads/2017/01/genderbread-social-card.png)

- Um desses métodos de documentação linguística está descrito em [**Redes sociais, variação linguística e polidez: procedimentos de coleta de dados**](https://openaccess.blucher.com.br/article-details/redes-sociais-variao-lingustica-e-polidez-procedimentos-de-coleta-de-dados-18958), desenvolvido em coautoria com a atual doutoranda e professora da Universidade Estadual de Santa Cruz [Andreia Silva Araujo](http://lattes.cnpq.br/9184573743061880) e [Kelly Carine do Santos](http://lattes.cnpq.br/1064867139869114). O protocolo foi empregado para descrever efeitos de polidez na primeira pessoa do plural, como no artigo [**Efeitos de polidez na variação na primeira pessoa do plural**](https://periodicos.ufjf.br/index.php/veredas/article/view/28150), publicado na revista Veredas e em coautoria com  [Kelly Carine do Santos](http://lattes.cnpq.br/1064867139869114), e [**Primeira pessoa do plural com referência genérica e a polidez linguística**](https://www.e-publicacoes.uerj.br/index.php/soletras/article/view/22491), publicado na revista Soletras e em coautoria com a doutoranda [Josilene de Jesus Mendonça](http://lattes.cnpq.br/7474484033588320).

- Também com o mesmo protocolo de coleta, no artigo [**Assalto ao turno em interações assimétricas de sexo/gênero: disputa e cooperação**](https://doi.org/10.26512/les.v20i1.11254), em coautoria com [Rebeca Rodrigues de Santana](http://lattes.cnpq.br/7843680671771834) e publicado na revista Linguagem & Sociedade, evidenciamos que o trabalho interacional de homens e mulheres é diferenciado, o que se evidencia por meio dos recursos linguísticos empregados pelos interactantes.

- Um trabalho de natureza etnográfica e de documentação de comunidades de práticas que tamb;em subsidiou o estudo de gênero foi o realizado por [Cristiane Santana Ribeiro](http://lattes.cnpq.br/6931574024597073) e [Thais Andrade Correa](http://lattes.cnpq.br/8838616973771031), no capítulo [**Relações de gênero e formas de tratamento em uma comunidade religiosa**](https://openaccess.blucher.com.br/article-details/relaes-de-gnero-e-formas-de-tratamento-em-uma-comunidade-religiosa-19665). Na [comunidade do Açuzinho](https://doi.org/10.21665/2318-3888.v2n3p194-217), um grupo religioso de mulheres, com uma líder mulher, tem padrões linguísticos das formas de tratamento ditados pelo único homem. 

- E em uma abordagem de percepção, no capítulo [**Inclusão, cooperação e gênero**](https://www.researchgate.net/publication/339339566_Genero_e_linguagem_formas_e_usos), do livro *Gênero e lingua(gem): formas e usos*, junto com [Josilene de Jesus Mendonça](http://lattes.cnpq.br/7474484033588320), são elicidadas as crenças subjacentes à escolha de pronomes possesivos de primeira pessoa do plural em função dos gêneros dos participantes.

Este projeto também envolveu uma equipe grande e fomentou a formação acadêmica de mestrado de [Andreia Silva Araujo](http://lattes.cnpq.br/9184573743061880) e [Josilene de Jesus Mendonça](http://lattes.cnpq.br/7474484033588320) (ambas atualmente doutorandas), [Kelly Carine do Santos](http://lattes.cnpq.br/1064867139869114), [Rebeca Rodrigues de Santana](http://lattes.cnpq.br/7843680671771834), [Cristiane Santana Ribeiro](http://lattes.cnpq.br/6931574024597073) e [Thaís Andrade Corrêa](http://lattes.cnpq.br/8838616973771031). 
</details>
<p>&nbsp;</p>
