---
title: "Questões de método: para uma Sociolinguística socialmente sensível"
---
Sistematicamente tenho oferecido cursos e treinamentos voltados ao compartilhamento de métodos de trabalho, de documentação linguística,  tratamento de dados e até escrita científica. Embora a oferta seja sistemática, o compatilhamento dos tutoriais era assistemático. Por isso decidi reuni-los neste repositório, com o objetivo de facilitar o acesso e ampliar o escopo de público.

Sigo a linha da Ciência Aberta, com o compartilhamento de instrumentos, colaboração em materiais e reuso de dados. Como nem tudo cabe no Lattes, eu narro a minha visão sobre aquilo que considero minhas melhores práticas, que não necessariamente são os produtos científicos mais importantes no Lattes, mas os que me permitiram refletir sobre minha carreira e o impacto da ciência. 

A necessidade de tantos tutoriais e instruções explícitas é inerente a mim: sou bagunceira e acumuladora, e gosto de trabalho em grandes grupos (nunca tive menos de 10 orientandos, a média é 20). Para manter a ordem, organização é essencial. E o desenvolvimento de todas essas ações só é possível pela estrutura do [Condomínio de Laboratórios Mulitusuário de Informática e Documentação Linguística](http://apoia.ufs.br/pagina/21072-condominio-de-laboratorios-multiusuarios-de-informatica-e-documentacao-lamid), sob minha coordenação, na Universidade Federal de Sergipe, que é fomentado por recursos advindos de projetos de pesquisa financiados pelas agências estaduais e federais. 

Uma **sociolinguística socialmente sensível** pode parecer redundante, tanto quanto *parto humanizado*. Afinal, tem coisa mais humana do que parir? tem coisa mais social do que língua? Mas, pelo menos no Brasil, existe um abismo entre a ciência e a realidade. A pesquisa sociolinguística brasileira ainda é modelada por limitações de método, com células sociais estratificadas homogeneamente e variáveis binárias por conta das especifidades de um modelo estatístico, reforçada especialmente pela replicação de práticas já automatizadas, como se fossem caixas e categorias pré-definidas onde os dados precisam ser acomodados. O resultado é a pouca expressividade e a pouca inserção social da sociolinguística nos programas de ensino e nos debates na sociedade brasileira. Em defesa de uma sociolinguística socialmente sensível, fui conferencista na 70^a^ edição da Reunião Anual da SBPC, em 2018, quando, a convite da Abralin, tratei do [**Ativismo sociolinguístico e suas contribuições para a construção de uma identidade linguística brasileira**](https://ufal.br/ufal/noticias/2018/7/debate-sobe-ativismo-sociolinguistico-exalta-a-importancia-da-pesquisa-cientifica-na-educacao-basica).

<details>
  <summary markdown="span"> **Clique aqui se quiser saber mais** </summary>
  
- [**A quarta onda: ativismo sociolinguístico no Brasil**](https://periodicos.ufsc.br/index.php/forum/article/view/92913/54464) relata uma trajetória de ações que permitem uma nova agenda de estudos da Sociolinguística no Brasil. [Aqui em inglês](https://periodicos.ufsc.br/index.php/forum/article/view/92913/54469)
 
 - Para entender melhor a questão da inserção da Sociolinguística no Brasil, convido à leitura do artigo [**Sociolinguística no/do Brasil**](https://doi.org/10.20396/cel.v58i3.8647170), publicado no dossiê da revista *Cadernos de Estudos Linguísticos* com o tema *50 Anos de Social Stratification of English in New York City*, organizado por [Livia Oushiro](https://oushiro.github.io/pt/), pesquisadora brasileira que também tem uma postura sociolinguística socialmente engajada e dedicada à questão dos métodos.

 - E para a questão metodológica, convido à leitura do artigo [**A dadidade (ou dadidão) do dado**](https://www.linguisticario.letras.ufrj.br/uploads/7/0/5/2/7052840/lr31_freitag.pdf), publicado em um dossiê dedicado à *formação do linguista* na revista Linguistica Rio, em que trato da entidade “dado linguístico”, já apontando para a organização de conjuntos de dados e suas implicações metodológicas.

</details>

