---
title: "Popularização da ciência"
---

## **Cienart**

Embora a educação para a ciência seja prevista como parte integrante do processo educacional, o Brasil tem se mostrado deficitário em suas metas educacionais em geral e na educação científica especificamente.
Apenas uma pequena parcela dos jovens brasileiros segue carreira em áreas científicas e tecnológicas. Para aumentar essa porcentagem, é necessário despertar desde cedo a motivação e a criatividade nos estudantes, ao mesmo tempo direcionando-os para o uso do método científico. Atividades de popularização da ciência, como feiras de ciências, fazem jovens e crianças refletirem e colocarem em prática o aprendizado, essencial na formação do futuro cientista, em qualquer área do conhecimento. A concretização dessas ações depende também da motivação e formação dos próprios professores, além da conscientização de coordenadores e diretores escolares para a inclusão destas práticas no calendário escolar. Também a colaboração e o apoio dos profissionais de centros de pesquisa e divulgação são fatores determinantes para o sucesso de tais empreendimentos.

É neste contexto que surge a [**Feira Estadual de Ciências, Tecnologia e Artes de Sergipe (Cienart)**](http://www.cienart-se.com.br), ação que organiza a Feira Científica de Sergipe, apoia professores na elaboração e submissão de projetos científicos para concorrerem a editais de agências de fomento com linhas específicas para a educação básica, e disponibiliza bolsas de iniciação científica júnior (IC Jr) aos alunos premiados durante a Feira Científica de Sergipe. 

Faço parte desta equipe multidisciplinar e engajada, organizando as ações e editando a revista [**Feira de Ciência & Cultura**](https://issuu.com/cienart.sergipe/docs/revista_vol5n7_2018_web), que publica artigos decorrentes de pesquisas científicas desenvolvidas na educação básica por al;unos e professores. Oferecer cursos para a elaboração de projetos de pesquisa para concorrer em editais de fomento, e de redação de artigos científicos são atividades que realizo anualmente no calendário de ações da **Cienart**.

## **Não basta fazer, tem que divulgar!**

Junto com meus orientandos, produzimos um vídeo para o concurso [Dance linguística](https://www.youtube.com/watch?v=oVbQlRCl48o), promovido pela Abralin, e fomos um dos vencedores. O artigo no qual o vídeo foi baseado, [**Estudo piloto da relação entre o julgamento de traços linguísticos e expressões faciais**](https://cadernos.abralin.org/index.php/cadernos/article/view/15). foi publicado na revista *Cadernos de Linguística*, o novo periódico da Abralin.

<iframe width="560" height="315"
src="https://www.youtube.com/watch?v=oVbQlRCl48o" 
frameborder="0" 
allow="Dance linguistica"
allowfullscreen></iframe>




